version: "3.8"

services:

  backend:
    restart: always
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    command: sh -c "python manage.py runserver 0.0.0.0:8000"

  engine:
    restart: always
    container_name: engine
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app/backend
    command: cron -f

  frontend:
    restart: always
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./frontend/public:/app/frontend/public
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    stdin_open: true
    command: npm start
