version: "3.8"
services:
  backend:
    restart: always
    container_name: backend
    command : bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
